/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useState, useRef } from "react";
import { useGLTF, ContactShadows } from "@react-three/drei";
import { useSpring, animated, config } from "@react-spring/three";

function ModelTruck(props) {
  const { nodes, materials } = useGLTF("/truck.glb");

  return (
    <>
      <group {...props} dispose={null}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes["1_wheel_0"].geometry}
                material={materials.wheel}
              />
            </group>
            <group
              position={[-0.25, 176.21, -1.85]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube_Org001_0.geometry}
                material={materials["Org.001"]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube_Org_0.geometry}
                material={materials.material}
              />
            </group>
            <group
              position={[0, 174.15, 0.12]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube001_Wht001_0.geometry}
                material={materials["Wht.001"]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube001_Wht_0.geometry}
                material={materials.material_2}
              />
            </group>
            <group
              position={[0, 172.79, -25.03]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube002_Org_0.geometry}
                material={materials.material}
              />
            </group>
            <group
              position={[-0.25, 256.37, -48.03]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube003_Org_0.geometry}
                material={materials.material}
              />
            </group>
            <group
              position={[-0.25, 274.17, -55.61]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube005_Org002_0.geometry}
                material={materials["Org.002"]}
              />
            </group>
            <group
              position={[-0.25, 278.79, -112.65]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube006_Org002_0.geometry}
                material={materials["Org.002"]}
              />
            </group>
            <group
              position={[-0.25, 175, -1.85]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube014_Metal_0.geometry}
                material={materials.Metal}
              />
            </group>
            <group
              position={[0, 68.81, 40.4]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube016_Black001_0.geometry}
                material={materials["Black.001"]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube016_Metal004_0.geometry}
                material={materials["Metal.004"]}
              />
            </group>
            <group
              position={[0.17, 273.7, -55.61]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube018_Org001_0.geometry}
                material={materials["Org.001"]}
              />
            </group>
            <group
              position={[7.63, 302.56, -76.24]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube019_Gold_0.geometry}
                material={materials.Gold}
              />
            </group>
            <group
              position={[-0.25, 266.72, -65.93]}
              rotation={[-1.6, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube020_Org006_0.geometry}
                material={materials["Org.006"]}
              />
            </group>
            <group
              position={[0, 174.15, 0.12]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube022_Metal_0.geometry}
                material={materials.Metal}
              />
            </group>
            <group
              position={[7.63, 302.74, -76.24]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube025_Org007_0.geometry}
                material={materials["Org.007"]}
              />
            </group>
            <group
              position={[-0.25, 267.93, -66.46]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube026_Org002_0.geometry}
                material={materials["Org.002"]}
              />
            </group>
            <group
              position={[-0.25, 65.4, -21.72]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube027_chassis002_0.geometry}
                material={materials["chassis.002"]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube027_chassis_0.geometry}
                material={materials.chassis}
              />
            </group>
            <group
              position={[-0.25, 128.3, -137.19]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube029_Door_0.geometry}
                material={materials.Door}
              />
            </group>
            <group
              position={[-0.25, 278.79, -112.65]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube030_Red_0.geometry}
                material={materials.material_20}
              />
            </group>
            <group
              position={[0, 68.81, 40.4]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube031_Gold_0.geometry}
                material={materials.Gold}
              />
            </group>
            <group
              position={[0, 68.81, 40.4]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube032_Metal_0.geometry}
                material={materials.Metal}
              />
            </group>
            <group
              position={[0, 68.81, 40.4]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube033_Org_0.geometry}
                material={materials.material}
              />
            </group>
            <group
              position={[-0.25, 210.53, -1.85]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube034_Org004_0.geometry}
                material={materials["Org.004"]}
              />
            </group>
            <group
              position={[-0.25, 176.21, -1.85]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube035_Black013_0.geometry}
                material={materials["Black.013"]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube035_Material001_0.geometry}
                material={materials["Material.002"]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube035_Org_0.geometry}
                material={materials.material}
              />
            </group>
            <group
              position={[0, 68.81, 40.4]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube036_Red_0.geometry}
                material={materials.material_20}
              />
            </group>
            <group
              position={[0, 254.84, -76.37]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube037_Org_0.geometry}
                material={materials.material}
              />
            </group>
            <group
              position={[7.63, 302.56, -76.24]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube038_SerMat_0.geometry}
                material={materials.SerMat}
              />
            </group>
            <group
              position={[-0.25, 161.28, -140.55]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube039_Metal_0.geometry}
                material={materials.Metal}
              />
            </group>
            <group
              position={[-0.25, 60.92, -21.72]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube053_chassis002_0.geometry}
                material={materials["chassis.002"]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube053_chassis_0.geometry}
                material={materials.chassis}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube054_Black_0.geometry}
                material={materials.Black}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube055_Black_0.geometry}
                material={materials.Black}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube056_Black_0.geometry}
                material={materials.Black}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube057_Black_0.geometry}
                material={materials.Black}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube058_Black_0.geometry}
                material={materials.Black}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube059_Black_0.geometry}
                material={materials.Black}
              />
            </group>
            <group
              position={[-0.25, 75.04, -13.24]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube060_Metal_0.geometry}
                material={materials.Metal}
              />
            </group>
            <group
              position={[-0.25, 51.9, -13.24]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube061_chassis1_0.geometry}
                material={materials.chassis1}
              />
            </group>
            <group
              position={[-0.25, 248.9, -59.1]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube072_Org_0.geometry}
                material={materials.material}
              />
            </group>
            <group
              position={[-0.25, 53.92, -13.24]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube073_chassis1001_0.geometry}
                material={materials["chassis1.001"]}
              />
            </group>
            <group
              position={[-0.25, 176.21, -1.85]}
              rotation={[0.11, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube074_Org_0.geometry}
                material={materials.material}
              />
            </group>
            <group
              position={[-0.25, 65.4, -21.72]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube075_chassis002_0.geometry}
                material={materials["chassis.002"]}
              />
            </group>
            <group
              position={[0, 174.15, 0.12]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube081_Metal_0.geometry}
                material={materials.Metal}
              />
            </group>
            <group
              position={[0, 74.8, -96.32]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube084_SerMat_0.geometry}
                material={materials.SerMat}
              />
            </group>
            <group
              position={[0, 113.04, -132.62]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube085_Metal002_0.geometry}
                material={materials["Metal.002"]}
              />
            </group>
            <group
              position={[0, 103.85, -145.49]}
              rotation={[-1.73, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube086_Metal002_0.geometry}
                material={materials["Metal.002"]}
              />
            </group>
            <group
              position={[0, 110.22, -145.49]}
              rotation={[-1.73, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube087_Metal002_0.geometry}
                material={materials["Metal.002"]}
              />
            </group>
            <group
              position={[-0.09, 173.43, 0.6]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube088_Metal007_0.geometry}
                material={materials["Metal.007"]}
              />
            </group>
            <group
              position={[-0.25, 175.78, 6.11]}
              rotation={[-1.43, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube091_Org009_0.geometry}
                material={materials["Org.009"]}
              />
            </group>
            <group
              position={[-0.25, 176.21, -1.85]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube092_Org004_0.geometry}
                material={materials["Org.004"]}
              />
            </group>
            <group
              position={[-0.25, 279.61, -112.96]}
              rotation={[-1.54, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube094_SerMat_0.geometry}
                material={materials.SerMat}
              />
            </group>
            <group
              position={[19.92, 301.01, -116.77]}
              rotation={[-1.68, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube095_SerMat_0.geometry}
                material={materials.SerMat}
              />
            </group>
            <group
              position={[19.92, 299.06, -133.99]}
              rotation={[-1.66, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube096_SerMat_0.geometry}
                material={materials.SerMat}
              />
            </group>
            <group
              position={[-0.25, 247.23, 95.54]}
              rotation={[-1.49, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube097_Black005_0.geometry}
                material={materials["Black.005"]}
              />
            </group>
            <group
              position={[-20.16, 300.23, -115.86]}
              rotation={[-1.68, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube098_SerMat_0.geometry}
                material={materials.SerMat}
              />
            </group>
            <group
              position={[-18.36, 270.85, 49.02]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube099_Black012_0.geometry}
                material={materials["Black.012"]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube099_em_0.geometry}
                material={materials.material_44}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube099_Org_0.geometry}
                material={materials.material}
              />
            </group>
            <group
              position={[-22.3, 266.58, 50.04]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube100_Org_0.geometry}
                material={materials.material}
              />
            </group>
            <group
              position={[-14.61, 266.58, 50.04]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube101_Org_0.geometry}
                material={materials.material}
              />
            </group>
            <group
              position={[-11.21, 149.02, 123.01]}
              rotation={[-0.15, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder_Metal_0.geometry}
                material={materials.Metal}
              />
            </group>
            <group
              position={[-16.04, 247.16, 25.94]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <group position={[0.07, -0.2, 0.12]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cylinder014_Org_0.geometry}
                  material={materials.material}
                />
              </group>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder015_Org001_0.geometry}
                material={materials["Org.001"]}
              />
              <group position={[-0.22, 0, 0.19]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cylinder016_Org001_0.geometry}
                  material={materials["Org.001"]}
                />
              </group>
              <group position={[0, 0, 0.22]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cylinder017_Org001_0.geometry}
                  material={materials["Org.001"]}
                />
              </group>
              <group position={[-0.2, 0, 0.2]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cylinder018_Org001_0.geometry}
                  material={materials["Org.001"]}
                />
              </group>
              <group position={[0, 0, -0.07]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.Cylinder019_Org001_0.geometry}
                  material={materials["Org.001"]}
                />
              </group>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder001_Org008_0.geometry}
                material={materials["Org.008"]}
              />
            </group>
            <group
              position={[-0.33, 198.81, 132.76]}
              rotation={[0.22, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder006_Metal006_0.geometry}
                material={materials["Metal.006"]}
              />
            </group>
            <group
              position={[-11.33, 150.51, 132.97]}
              rotation={[2.99, 0, -0.02]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder007_Metal_0.geometry}
                material={materials.Metal}
              />
            </group>
            <group
              position={[-11.2, 148.82, 122.32]}
              rotation={[-0.15, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder008_Metal_0.geometry}
                material={materials.Metal}
              />
            </group>
            <group
              position={[-0.25, 230.51, 132.8]}
              rotation={[-1.18, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder009_Metal003_0.geometry}
                material={materials["Metal.003"]}
              />
            </group>
            <group
              position={[-11.1, 149.7, 128.14]}
              rotation={[-0.16, -0.01, 1.57]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder010_Metal_0.geometry}
                material={materials.Metal}
              />
            </group>
            <group
              position={[-11.21, 149.02, 123.01]}
              rotation={[-0.15, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder011_Gold_0.geometry}
                material={materials.Gold}
              />
            </group>
            <group
              position={[-0.25, 230.44, 132.77]}
              rotation={[-1.18, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder013_Material_0.geometry}
                material={materials["Material.001"]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder013_Metal_0.geometry}
                material={materials.Metal}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder013_Yel_0.geometry}
                material={materials.material_12}
              />
            </group>
            <group
              position={[7.51, 311.27, -71.92]}
              rotation={[-0.68, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder020_Yel_0.geometry}
                material={materials.material_12}
              />
            </group>
            <group
              position={[7.51, 311.27, -71.92]}
              rotation={[-0.68, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder022_Black002_0.geometry}
                material={materials["Black.002"]}
              />
            </group>
            <group
              position={[7.51, 311.27, -71.92]}
              rotation={[-0.68, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder023_wh_s_0.geometry}
                material={materials.wh_s}
              />
            </group>
            <group
              position={[6.2, 326.39, -65.36]}
              rotation={[-0.68, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder024_wh_s_0.geometry}
                material={materials.wh_s}
              />
            </group>
            <group
              position={[0.01, 79.64, 81.37]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder036_Metal_0.geometry}
                material={materials.Metal}
              />
            </group>
            <group
              position={[0.01, 82.54, 81.37]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder037_Metal_0.geometry}
                material={materials.Metal}
              />
            </group>
            <group
              position={[0.03, 110.56, 109.5]}
              rotation={[-2.08, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder038_Metal_0.geometry}
                material={materials.Metal}
              />
            </group>
            <group
              position={[0, 0, -24.85]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder058_chassis_0.geometry}
                material={materials.chassis}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder083_Black_0.geometry}
                material={materials.Black}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder084_wheel_0.geometry}
                material={materials.wheel}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder085_Org003_0.geometry}
                material={materials["Org.003"]}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder087_Org003_0.geometry}
                material={materials["Org.003"]}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder088_Black_0.geometry}
                material={materials.Black}
              />
            </group>
            <group
              position={[0, 0, -197.16]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder089_Black014_0.geometry}
                material={materials["Black.014"]}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder097_Black010_0.geometry}
                material={materials["Black.010"]}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder098_Black_0.geometry}
                material={materials.Black}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder099_Black_0.geometry}
                material={materials.Black}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder100_Black_0.geometry}
                material={materials.Black}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder101_SerMat_0.geometry}
                material={materials.SerMat}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder102_Black_0.geometry}
                material={materials.Black}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder103_Black_0.geometry}
                material={materials.Black}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder104_chassis_0.geometry}
                material={materials.chassis}
              />
            </group>
            <group
              position={[15.57, 59.88, 45.76]}
              rotation={[0.11, -1.14, -0.26]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder105_Black_0.geometry}
                material={materials.Black}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder106_Black_0.geometry}
                material={materials.Black}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder107_Black_0.geometry}
                material={materials.Black}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder109_Black_0.geometry}
                material={materials.Black}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder110_Black010_0.geometry}
                material={materials["Black.010"]}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder111_Black_0.geometry}
                material={materials.Black}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder112_Black_0.geometry}
                material={materials.Black}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder113_Black_0.geometry}
                material={materials.Black}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder114_Black_0.geometry}
                material={materials.Black}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder115_Black_0.geometry}
                material={materials.Black}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder117_Black_0.geometry}
                material={materials.Black}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder118_Black_0.geometry}
                material={materials.Black}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder120_Black_0.geometry}
                material={materials.Black}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder121_Black_0.geometry}
                material={materials.Black}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder122_Black_0.geometry}
                material={materials.Black}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder123_Black_0.geometry}
                material={materials.Black}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder124_Black_0.geometry}
                material={materials.Black}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder125_Black_0.geometry}
                material={materials.Black}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder126_Black_0.geometry}
                material={materials.Black}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder127_Black_0.geometry}
                material={materials.Black}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder128_Black_0.geometry}
                material={materials.Black}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder129_Black_0.geometry}
                material={materials.Black}
              />
            </group>
            <group
              position={[-16.04, 247.16, 25.94]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder219_Org_0.geometry}
                material={materials.material}
              />
            </group>
            <group
              position={[-0.33, 198.81, 132.76]}
              rotation={[0.22, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder220_Metal_0.geometry}
                material={materials.Metal}
              />
            </group>
            <group
              position={[-0.33, 198.81, 132.76]}
              rotation={[0.22, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder221_Metal_0.geometry}
                material={materials.Metal}
              />
            </group>
            <group
              position={[-33.18, 260.82, -19.2]}
              rotation={[-1.31, -0.86, -1.23]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder222_Black002_0.geometry}
                material={materials["Black.002"]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder222_Black008_0.geometry}
                material={materials["Black.008"]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder222_Black009_0.geometry}
                material={materials["Black.009"]}
              />
            </group>
            <group
              position={[-0.25, 176.21, -1.85]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder223_SerMat_0.geometry}
                material={materials.SerMat}
              />
            </group>
            <group
              position={[-0.25, 176.21, -1.85]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder224_SerMat_0.geometry}
                material={materials.SerMat}
              />
            </group>
            <group
              position={[-0.25, 176.21, -1.85]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder225_SerMat_0.geometry}
                material={materials.SerMat}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder227_Black014_0.geometry}
                material={materials["Black.014"]}
              />
            </group>
            <group
              position={[-20.27, 252.31, -95.44]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder228_Metal_0.geometry}
                material={materials.Metal}
              />
            </group>
            <group
              position={[-15.05, 176.85, 134.75]}
              rotation={[0.21, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder229_Metal005_0.geometry}
                material={materials["Metal.005"]}
              />
            </group>
            <group
              position={[-26.84, 242.69, 133.16]}
              rotation={[-2.95, -0.09, -0.86]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder230_Black004_0.geometry}
                material={materials["Black.004"]}
              />
            </group>
            <group
              position={[-0.25, 176.21, -1.85]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder231_SerMat_0.geometry}
                material={materials.SerMat}
              />
            </group>
            <group
              position={[17.47, 149.61, 133.14]}
              rotation={[0.22, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cylinder234_Metal_0.geometry}
                material={materials.Metal}
              />
            </group>
            <group
              position={[26.53, 185.39, 140.73]}
              rotation={[0.62, -1, 2.05]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.NurbsPath001_Stairs001_0.geometry}
                material={materials["Stairs.001"]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.NurbsPath001_Stairs_0.geometry}
                material={materials.Stairs}
              />
            </group>
            <group
              position={[-52.21, 226.42, 27.1]}
              rotation={[-1.5, -1.37, -1.54]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.NurbsPath002_Stairs001_0.geometry}
                material={materials["Stairs.001"]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.NurbsPath002_Stairs_0.geometry}
                material={materials.Stairs}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.NurbsPath003_Black_0.geometry}
                material={materials.Black}
              />
            </group>
            <group
              position={[-0.25, 53.92, -13.24]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.NurbsPath004_Black_0.geometry}
                material={materials.Black}
              />
            </group>
            <group
              position={[-0.31, 53.77, -14.26]}
              rotation={[-Math.PI / 2, 0, -Math.PI]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.NurbsPath005_Black_0.geometry}
                material={materials.Black}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.NurbsPath006_Black_0.geometry}
                material={materials.Black}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.NurbsPath007_Black011_0.geometry}
                material={materials["Black.011"]}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.NurbsPath009_Black011_0.geometry}
                material={materials["Black.011"]}
              />
            </group>
            <group
              position={[-0.25, 176.21, -1.85]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.NurbsPath011_SerMat_0.geometry}
                material={materials.SerMat}
              />
            </group>
            <group
              position={[-27.1, 243.23, 121.48]}
              rotation={[-Math.PI / 2, 0, Math.PI / 2]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.NurbsPath012_Black006_0.geometry}
                material={materials["Black.006"]}
              />
            </group>
            <group
              position={[26.53, 185.39, 140.73]}
              rotation={[0.62, -1, 2.05]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.NurbsPath013_Org005_0.geometry}
                material={materials["Org.005"]}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Nut002_Metal001_0.geometry}
                material={materials["Metal.001"]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Nut002_Metal001_0001.geometry}
                material={materials["Metal.001"]}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Nut003_Metal001_0.geometry}
                material={materials["Metal.001"]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Nut003_Metal001_0001.geometry}
                material={materials["Metal.001"]}
              />
            </group>
            <group
              position={[-0.25, 176.21, -1.85]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane_Org_0.geometry}
                material={materials.material}
              />
            </group>
            <group
              position={[-0.25, 202.68, -1.85]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane001_Org004_0.geometry}
                material={materials["Org.004"]}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane025_Black_0.geometry}
                material={materials.Black}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane026_Black_0.geometry}
                material={materials.Black}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane027_chassis1_0.geometry}
                material={materials.chassis1}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane028_Black_0.geometry}
                material={materials.Black}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane029_chassis1_0.geometry}
                material={materials.chassis1}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane030_chassis1_0.geometry}
                material={materials.chassis1}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane031_chassis_0.geometry}
                material={materials.chassis}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane032_chassis_0.geometry}
                material={materials.chassis}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane033_Black_0.geometry}
                material={materials.Black}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane034_Black_0.geometry}
                material={materials.Black}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane035_chassis1_0.geometry}
                material={materials.chassis1}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane036_Black_0.geometry}
                material={materials.Black}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane037_chassis1_0.geometry}
                material={materials.chassis1}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane038_chassis1_0.geometry}
                material={materials.chassis1}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane039_chassis_0.geometry}
                material={materials.chassis}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane040_chassis_0.geometry}
                material={materials.chassis}
              />
            </group>
            <group
              position={[-43.34, 187.07, 111.38]}
              rotation={[0.11, 0, -0.14]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane074_Org_0.geometry}
                material={materials.material}
              />
            </group>
            <group
              position={[0, 174.15, 0.12]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane075_Metal_0.geometry}
                material={materials.Metal}
              />
            </group>
            <group
              position={[0, 221.77, 0.12]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane076_Org_0.geometry}
                material={materials.material}
              />
            </group>
            <group
              position={[-0.25, 176.21, -1.85]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane078_Org004_0.geometry}
                material={materials["Org.004"]}
              />
            </group>
            <group
              position={[-0.25, 230.08, -201.53]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane079_Org_0.geometry}
                material={materials.material}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Sphere011_Black003_0.geometry}
                material={materials["Black.003"]}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Sphere012_Black_0.geometry}
                material={materials.Black}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Sphere014_Black003_0.geometry}
                material={materials["Black.003"]}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Sphere015_Black_0.geometry}
                material={materials.Black}
              />
            </group>
            <group
              position={[-0.25, 176.21, -1.85]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Sphere032_Ball_0.geometry}
                material={materials.Ball}
              />
            </group>
            <ContactShadows
              scale={10}
              far={3}
              blur={3}
              rotation={[Math.PI / 2, 0, 0]}
              color={"#2A8AFF"}
            />
          </group>
        </group>
      </group>
    </>
  );
}

export function MovingTruck({ onTargetChange }) {
  const myMesh = useRef();
  const [active, setActive] = useState(false);
  const { scale } = useSpring({
    scale: active ? 1 : 1.5,
    config: config.wobbly,
  });

  return (
    <animated.mesh
      ref={myMesh}
      scale={scale}
      onClick={() => setActive(!active)}
    >
      <ModelTruck
        scale={0.008}
        position={[-10, -3.4, -4]}
        rotation-y={Math.PI / 4}
        castShadow
        receiveShadow
      />
    </animated.mesh>
  );
}

useGLTF.preload("/truck.glb");
